# Generated by Django 5.1.2 on 2024-10-30 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('tipo_usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Tratamientos',
            fields=[
                ('tratamiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(default='')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_inicio', models.DateField(default='1900-01-01')),
                ('fecha_fin', models.DateField(default='1900-01-01')),
            ],
            options={
                'db_table': 'tratamientos',
            },
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='fk_generos',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(default='', max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
            options={
                'db_table': 'doctores',
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('paciente_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(default='1900-01-01')),
                ('direccion', models.CharField(default='', max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('cita_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default='1900-01-01')),
                ('hora', models.TimeField(default='00:00')),
                ('descripcion', models.CharField(default='', max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctores')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pacientes')),
            ],
            options={
                'db_table': 'citas',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default='1900-01-01')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20)),
                ('descripcion', models.CharField(default='', max_length=255)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('no pagado', 'No Pagado')], default='pendiente', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pacientes')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.AddField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.tipousuario'),
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('historial_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default='1900-01-01')),
                ('descripcion', models.TextField(default='')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctores')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pacientes')),
                ('tratamientos', models.ManyToManyField(to='api.tratamientos')),
            ],
            options={
                'db_table': 'historial_medico',
            },
        ),
        migrations.DeleteModel(
            name='Generos',
        ),
    ]
