# Generated by Django 5.1.2 on 2024-11-09 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_usuarios_usuario_id_usuarios_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tratamientos'),
        ),
    ]
