# Generated by Django 5.1.2 on 2024-11-09 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_citas_tratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('especialidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'especialidades',
            },
        ),
        migrations.AlterField(
            model_name='doctores',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especialidad'),
        ),
    ]
