# Generated by Django 5.1.2 on 2024-11-09 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_especialidad_alter_doctores_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTratamiento',
            fields=[
                ('tipo_tratamiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_tratamiento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_tratamiento',
            },
        ),
        migrations.AddField(
            model_name='tratamientos',
            name='tipo_tratamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.tipotratamiento'),
        ),
    ]
