# Generated by Django 5.1.4 on 2024-12-07 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_citas_comentarios_citas_servicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('medicamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'medicamentos',
            },
        ),
        migrations.AddField(
            model_name='pagos',
            name='cita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.citas'),
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('notificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('correo', 'Correo electrónico'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('leida', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pacientes')),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
        migrations.CreateModel(
            name='RegistrosClinicos',
            fields=[
                ('registro_clinico_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en kilogramos', max_digits=5)),
                ('estatura', models.DecimalField(decimal_places=2, help_text='Estatura en metros', max_digits=4)),
                ('presion_sistolica', models.IntegerField(help_text='Presión sistólica en mmHg')),
                ('presion_diastolica', models.IntegerField(help_text='Presión diastólica en mmHg')),
                ('frecuencia_cardiaca', models.IntegerField(help_text='Latidos por minuto (LPM)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('saturacion_oxigeno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pacientes')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
            options={
                'db_table': 'registros_clinicos',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoTratamiento',
            fields=[
                ('seguimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_seguimiento', models.DateField()),
                ('dosis', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(default='En curso', max_length=50)),
                ('observaciones', models.TextField()),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medicamentos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pacientes')),
            ],
            options={
                'db_table': 'seguimiento_tratamiento',
            },
        ),
    ]
