# Generated by Django 5.1.3 on 2024-12-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_medicamentos_notificaciones_registrosclinicos_and_more'),
        ('api', '0008_medicamentos_pagos_cita_notificaciones_and_more'),
    ]

    operations = [
    ]
